const Icon = {
  home: require('./icons/home.png'),
  Minis: require('./icons/minis.png'),
  Trends: require('./icons/trends.png'),
  Bag: require('./icons/bag.png'),
  pumalogo: require('./icons/pumalogo.png'),
  downarrow: require('./icons/downarrow.png'),
  crown: require('./icons/crown.png'),
  bell: require('./icons/bell.png'),
  heart: require('./icons/heart.png'),
  profile: require('./icons/profile.png'),
  microphone: require('./icons/microphone.png'),
  camera: require('./icons/camera.png'),
  search: require('./icons/search.png'),
  back: require('./icons/back.png'),
  share: require('./icons/share.png'),
  secure: require('./icons/secure.png'),
  cod: require('./icons/cod.png'),
  return: require('./icons/return.png'),
  close: require('./icons/close.png'),
  favorite: require('./icons/favorite.png'),
  profile2: require('./icons/profile2.png'),
  order: require('./icons/order.png'),
  next: require('./icons/next.png'),
  qr: require('./icons/qr.png'),
  support: require('./icons/support.png'),
  eye: require('./icons/eye.png'),
  eyeoff: require('./icons/eyeoff.png'),
  levislogo: require('./icons/levislogo.jpg'),
  pause: require('./icons/pause.png'),
  bookmark: require('./icons/bookmark.png'),



};
const Images = {
  emptycart: require('./images/emptycart.png'),
  boy: require('./images/boy.jpeg'),
  jeans: require('./images/jeans.jpg'),
  bedsheet: require('./images/bedsheet.jpeg'),
  jacket: require('./images/jacket.jpg'),
  tshirt: require('./images/tshirt.jpg'),
  watch: require('./images/watch.jpg'),
  shoes: require('./images/shoes.jpg'),
  gtshirt: require('./images/gtshirt.jpg'),
  gjeans: require('./images/gjeans.jpg'),
  gjacket: require('./images/gjacket.jpg'),
  kurta: require('./images/gkurta.jpg'),
  lipstick: require('./images/lipstick.jpg'),
  top: require('./images/tops.jpg'),
  banner1: require('./images/banner1.png'),
  banner2: require('./images/banner2.png'),
  banner3: require('./images/banner3.png'),
  banner4: require('./images/banner4.png'),
  banner5: require('./images/banner5.png'),
  emptylist: require('./images/emptylist.png'),
  
};
export {Icon, Images};
